name: realfusion 
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip
  - numpy>=1.20
  - click>=8.0
  - pillow
  - scipy
  - pytorch=1.11.0
  - torchvision
  - cudatoolkit=11.3
  - requests
  - setuptools
  - tqdm
  - ninja
  - matplotlib
  - imageio
  - pip:
    - imgui
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - psutil
    - mrcfile
    - tensorboard
    - gdown
    - opencv-python
